### ISSUE TITLE
Pogreb incompatible with arm/arm64

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/hmap#45]
## Description
`https://github.com/akrylysov/pogreb` is not compatible with windows arm/arm64 since the constant `maxMmapSize` is not defined
The temporary solution was to disable arm/arm64 compilation for windows platforms with the following goreleaser snippet:
```yaml
ignore:
        - goos: windows
          goarch: 'arm'
        - goos: windows
          goarch: 'arm64'
```
The project seems not active, hence we have to check if send a patch upstream or fork and maintain
